version: '3.8'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev